apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-web-app-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/CodeByAshB/go-web-app.git
    targetRevision: main
    path: helm/go-web-app-chart
    helm:
      valueFiles:
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      jsonPointers:
        - /status

